language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  #- 'echo "deb http://archive.ubuntu.com/ubuntu/ saucy main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list'
  - "sudo apt-get update -qq"
install: 
  - "pip install pep8 python-coveralls pyflakes --use-mirrors"
  - "rm $VIRTUAL_ENV/lib/*/no-global-site-packages.txt"
  - "sudo apt-get install -qq python-gi gtk-3-examples gir1.2-gtk-3.0 python-gi-cairo gsettings-desktop-schemas python-pyatspi python-dbus at-spi2-core libatk-adaptor gnome-screenshot language-pack-gnome-en"
  - "gsettings set org.gnome.desktop.interface toolkit-accessibility true"
script:
  - "pyflakes dogtail scripts tests"
  - "pep8 --max-line-length=120 dogtail scripts tests"
  - "nosetests --with-coverage --cover-package=dogtail -v"
  - "python setup.py install"
after_success:
  - coveralls
