language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'echo "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list'
  - "sudo apt-get update -qq"
  - "pip install pep8 python-coveralls pyflakes"
  - "pip install pygobject"
  - "pip install pycairo"
install: 
  - "gsettings set org.gnome.desktop.interface toolkit-accessibility true"
  - "sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq -y -o Dpkg::Options::='--force-confnew' python-gi python3-gi gtk-3-examples gir1.2-gtk-3.0 python-gi-cairo python3-gi-cairo python-dev python3-dev gsettings-desktop-schemas python-pyatspi python3-pyatspi python-gobject python3-gobject python-dbus python3-dbus at-spi2-core libatk-adaptor gnome-screenshot language-pack-gnome-en"
script:
  - "pyflakes dogtail scripts tests"
  - "pep8 --max-line-length=120 dogtail scripts tests"
  - "nosetests --with-coverage --cover-package=dogtail -v"
  - "python setup.py install"
after_success:
  - coveralls
